import { readFileSync, writeFileSync, existsSync, mkdirSync, chmodSync } from 'fs';
import { homedir } from 'os';
import { join } from 'path';
import { idToSlug } from '@skyrepl/contracts';
import type { ApiClient } from './client';

// =============================================================================
// Paths
// =============================================================================

const HOME = homedir();
const REPL_DIR = join(HOME, '.repl');
const SSH_CONFIG_PATH = join(REPL_DIR, 'ssh_config');
const USER_SSH_CONFIG = join(HOME, '.ssh', 'config');
const INCLUDE_LINE = 'Include ~/.repl/ssh_config';

// =============================================================================
// SSH Accessibility Check
// =============================================================================

/**
 * Returns true if an allocation is SSH-accessible:
 * - ACTIVE allocations are always accessible.
 * - COMPLETE allocations are accessible only while debug_hold_until is in the future.
 */
function isSSHAccessible(alloc: {
  status: string;
  debug_hold_until: number | null;
}): boolean {
  if (alloc.status === 'ACTIVE') return true;
  if (alloc.status === 'COMPLETE' && alloc.debug_hold_until !== null && alloc.debug_hold_until > Date.now()) {
    return true;
  }
  return false;
}

// =============================================================================
// Host Entry Generation
// =============================================================================

/**
 * Generate a single SSH Host block for one allocation.
 * Uses full base36 allocation ID as the slug.
 */
function generateHostEntry(alloc: {
  id: number;
  instance_ip: string | null;
  user: string;
  workdir: string;
}): string {
  const slug = idToSlug(alloc.id);
  const ip = alloc.instance_ip ?? '0.0.0.0';
  const lines = [
    `Host repl-${slug}`,
    `  HostName ${ip}`,
    `  User ${alloc.user || 'root'}`,
    `  Port 22`,
    `  StrictHostKeyChecking no`,
    `  UserKnownHostsFile /dev/null`,
    `  LogLevel ERROR`,
    `  RequestTTY yes`,
    `  ProxyCommand ~/.repl/bin/ssh_proxy.sh %h`,
  ];
  if (alloc.workdir) {
    lines.push(`  RemoteCommand cd ${alloc.workdir} && exec $SHELL -l`);
  }
  return lines.join('\n');
}

/** The catch-all entry that must appear LAST in the file. */
const CATCH_ALL_ENTRY = `Host repl-*
  ProxyCommand ~/.repl/bin/ssh_fallback.sh %n`;

// =============================================================================
// Public API
// =============================================================================

/**
 * Query the control plane for all SSH-accessible allocations and write
 * ~/.repl/ssh_config with per-allocation Host entries.
 *
 * Returns the count of per-allocation entries written (excludes catch-all).
 */
export async function regenerateSSHConfig(client: ApiClient): Promise<number> {
  const { data: allocations } = await client.listAllocations();

  // Filter to SSH-accessible allocations that have an IP
  const sshAllocations = allocations.filter((a: any) => isSSHAccessible(a));

  // Build config content: per-allocation entries first, catch-all last
  const hostEntries = sshAllocations.map((a: any) => generateHostEntry(a));

  const header = [
    '# SkyREPL SSH Config',
    `# Generated: ${new Date().toISOString()}`,
    '# Do not edit manually — regenerated by `repl ssh-config`',
    '',
  ].join('\n');

  const sections = [header, ...hostEntries, CATCH_ALL_ENTRY];
  const configContent = sections.join('\n\n') + '\n';

  // Ensure ~/.repl exists
  mkdirSync(REPL_DIR, { recursive: true });

  writeFileSync(SSH_CONFIG_PATH, configContent, { encoding: 'utf-8' });
  // chmod 600: contains IPs; no keys but still sensitive
  chmodSync(SSH_CONFIG_PATH, 0o600);

  return sshAllocations.length;
}

/**
 * Ensure ~/.ssh/config contains `Include ~/.repl/ssh_config` at the top.
 * SSH reads config top-down; Include must precede any Host entries it affects.
 *
 * Returns true if the file was modified, false if Include was already present.
 */
export async function ensureSSHConfigInclude(): Promise<boolean> {
  // Ensure ~/.ssh directory exists
  const sshDir = join(HOME, '.ssh');
  mkdirSync(sshDir, { recursive: true });

  let existing = '';
  if (existsSync(USER_SSH_CONFIG)) {
    existing = readFileSync(USER_SSH_CONFIG, 'utf-8');
  }

  // Check for Include line (any whitespace variant)
  const alreadyIncluded = existing.split('\n').some(
    (line) => line.trim() === INCLUDE_LINE
  );

  if (alreadyIncluded) {
    return false;
  }

  // Prepend Include line. SSH requires Include at the top to affect
  // subsequent Host blocks in the same file.
  const newContent = INCLUDE_LINE + '\n' + (existing ? existing : '');
  writeFileSync(USER_SSH_CONFIG, newContent, { encoding: 'utf-8' });

  return true;
}
